# Generated by Django 6.0.1 on 2026-04-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('producer_id', models.IntegerField()),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('color_score', models.FloatField()),
                ('size_score', models.FloatField()),
                ('ripeness_score', models.FloatField()),
                ('predicted_grade', models.CharField(max_length=4)),
                ('producer_accepted', models.BooleanField(blank=True, null=True)),
                ('override_grade', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
