import os
import pandas as pd
import numpy as np
import joblib
import tensorflow as tf
import logging

logger = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Paths to the artifacts generated by the training script
MODEL_PATH = os.path.join(BASE_DIR, 'quick_reorder_lstm.keras')
SCALER_PATH = os.path.join(BASE_DIR, 'lstm_scaler.pkl')
PROD_FEATURES_PATH = os.path.join(BASE_DIR, 'prod_features.pkl')

# Data fallbacks (CSV exports from DESD)
USER_FEATURES_CSV = os.path.join(BASE_DIR, "user_features.csv")
UP_FEATURES_CSV = os.path.join(BASE_DIR, "user_product_features.csv")

_model = None
_scaler = None
_prod_features = None

def _load_assets():
    global _model, _scaler, _prod_features
    if _model is None:
        try:
            logger.info("Loading Next Basket Model...")
            _model = tf.keras.models.load_model(MODEL_PATH)
            _scaler = joblib.load(SCALER_PATH)
            # prod_features is a dataframe of product-level stats
            if os.path.exists(PROD_FEATURES_PATH):
                _prod_features = pd.read_pickle(PROD_FEATURES_PATH)
            else:
                _prod_features = pd.DataFrame(columns=['product_id', 'prod_total_purchases', 'prod_reorder_rate'])
        except Exception as e:
            logger.error(f"Failed to load Next Basket assets: {e}")
            return False
    return True

def predict_next_basket(user_id, top_n=5):
    """
    Predicts the likelihood of purchase for items previously bought by the user.
    """
    if not _load_assets():
        return {"error": "Model assets not available"}

    # 1. Load User and User-Product features (the "Feature Store" snapshot)
    if not os.path.exists(USER_FEATURES_CSV) or not os.path.exists(UP_FEATURES_CSV):
        return {"error": "Feature snapshots missing. Please run a 'Next Basket Export' from DESD."}

    user_df = pd.read_csv(USER_FEATURES_CSV)
    up_df = pd.read_csv(UP_FEATURES_CSV)

    # Filter for this specific user
    user_data = user_df[user_df['user_id'] == user_id]
    user_prod_data = up_df[up_df['user_id'] == user_id]

    if user_data.empty or user_prod_data.empty:
        return {"error": f"No history found for user {user_id}"}

    # 2. Merge with Product Features
    df = user_prod_data.merge(user_data, on='user_id')
    df = df.merge(_prod_features, on='product_id', how='left').fillna(0)

    # 3. Engineer live feature: orders_since_last_purchase
    # Calculation: total_orders - last_order_num
    df['orders_since_last_purchase'] = df['user_total_orders'] - df['up_last_order_num']

    # 4. Prepare for Inference
    # The model was trained on: [up_total_bought, user_total_orders, user_avg_days_between, prod_total_purchases, prod_reorder_rate, orders_since_last_purchase]
    feature_cols = [
        'up_total_bought', 
        'user_total_orders', 
        'user_avg_days_between', 
        'prod_total_purchases', 
        'prod_reorder_rate', 
        'orders_since_last_purchase'
    ]
    
    X = df[feature_cols]
    X_scaled = _scaler.transform(X)
    X_lstm = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))

    # 5. Predict
    probs = _model.predict(X_lstm).ravel()
    df['score'] = probs

    # 6. Format Output
    recommendations = df.sort_values('score', ascending=False).head(top_n)
    
    result = []
    for _, row in recommendations.iterrows():
        result.append({
            "product_id": int(row['product_id']),
            "product_name": str(row.get('product_name', f"Product {int(row['product_id'])}")),
            "confidence": round(float(row['score']), 3),
            "reorder_probability": "High" if row['score'] > 0.7 else "Medium" if row['score'] > 0.4 else "Low"
        })

    return result
