import os
import pandas as pd
import numpy as np
import joblib
import tensorflow as tf
import logging

logger = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Subdirectories for data organization
PRODUCTION_DATA_DIR = os.path.join(BASE_DIR, "production_data")
INSTACART_DATA_DIR = os.path.join(BASE_DIR, "instacart_data")

# Paths to the artifacts generated by the training script (Brain)
MODEL_PATH = os.path.join(BASE_DIR, 'quick_reorder_lstm.keras')
SCALER_PATH = os.path.join(BASE_DIR, 'lstm_scaler.pkl')
PROD_FEATURES_PKL = os.path.join(BASE_DIR, 'prod_features.pkl')

# Data snapshots for inference (Short-Term Memory)
USER_FEATURES_CSV = os.path.join(PRODUCTION_DATA_DIR, "user_features.csv")
UP_FEATURES_CSV = os.path.join(PRODUCTION_DATA_DIR, "user_product_features.csv")
PROD_FEATURES_CSV = os.path.join(PRODUCTION_DATA_DIR, "prod_features.csv")

_model = None
_scaler = None
_prod_features = None

def _load_assets():
    global _model, _scaler, _prod_features
    if _model is None:
        try:
            logger.info("Loading Next Basket Model...")
            _model = tf.keras.models.load_model(MODEL_PATH)
            _scaler = joblib.load(SCALER_PATH)
            # prod_features is a dataframe of product-level stats
            # Prioritise the fresh CSV export from DESD, fall back to the training pickle
            if os.path.exists(PROD_FEATURES_CSV):
                _prod_features = pd.read_csv(PROD_FEATURES_CSV)
                print("Using prod_features.csv for product-level stats.")
            elif os.path.exists(PROD_FEATURES_PKL):
                _prod_features = pd.read_pickle(PROD_FEATURES_PKL)
                print("Using prod_features.pkl for product-level stats.")
            else:
                _prod_features = pd.DataFrame(columns=['product_id', 'prod_total_purchases', 'prod_reorder_rate'])
                print("Using empty DataFrame for product-level stats.")
        except Exception as e:
            logger.error(f"Failed to load Next Basket assets: {e}")
            return False
    return True

def predict_next_basket(user_id=None, top_n=5, demo_mode=False):
    """
    Predicts the likelihood of purchase for items previously bought by the user.
    """
    if not _load_assets():
        return {"error": "Model assets not available"}

    # 1. Load User and User-Product features (the "Feature Store" snapshot)
    if demo_mode:
        logger.info("Running in DEMO MODE using sample CSVs from instacart_data/...")
        
        if not os.path.exists(os.path.join(INSTACART_DATA_DIR, 'orders.csv')):
             return {"error": f"Demo data (orders.csv) not found in {INSTACART_DATA_DIR}"}

        # Load a sample user if none provided (ID 42 is a classic from this dataset)
        if not user_id:
            user_id = 42
            
        # [Simplified Demo Logic: Load from raw CSVs just like the notebook]
        orders = pd.read_csv(os.path.join(INSTACART_DATA_DIR, 'orders.csv'))
        prior = pd.read_csv(os.path.join(INSTACART_DATA_DIR, 'order_products__prior.csv'))
        
        user_data = orders[orders['user_id'] == user_id]
        if user_data.empty:
            return {"error": f"Demo user {user_id} not found in orders.csv"}

        # Calculate features on the fly for demo
        user_total_orders = user_data['order_number'].max()
        user_avg_days_between = user_data['days_since_prior_order'].mean()
        
        user_features = pd.DataFrame([{
            'user_id': user_id, 
            'user_total_orders': user_total_orders, 
            'user_avg_days_between': user_avg_days_between
        }])
        
        prior_orders = prior.merge(user_data[['order_id', 'user_id', 'order_number']], on='order_id')
        up_features = prior_orders.groupby(['user_id', 'product_id']).agg(
            up_total_bought=('order_id', 'count'),
            up_last_order_num=('order_number', 'max')
        ).reset_index()
        
        user_data = user_features
        user_prod_data = up_features
    else:
        if not os.path.exists(USER_FEATURES_CSV) or not os.path.exists(UP_FEATURES_CSV):
            return {"error": "Feature snapshots missing. Please run a 'Next Basket Export' from DESD."}

        if not user_id:
            return {"error": "customer_id is required for production mode."}

        user_df = pd.read_csv(USER_FEATURES_CSV)
        up_df = pd.read_csv(UP_FEATURES_CSV)

        # Filter for this specific user
        user_data = user_df[user_df['user_id'] == user_id]
        user_prod_data = up_df[up_df['user_id'] == user_id]

    if user_data.empty or user_prod_data.empty:
        return {"error": f"No history found for user {user_id}"}

    # 2. Merge with Product Features
    df = user_prod_data.merge(user_data, on='user_id')
    df = df.merge(_prod_features, on='product_id', how='left').fillna(0)

    # 3. Engineer live feature: orders_since_last_purchase
    # Calculation: total_orders - last_order_num
    df['orders_since_last_purchase'] = df['user_total_orders'] - df['up_last_order_num']

    # 4. Prepare for Inference
    # The model was trained on: [up_total_bought, user_total_orders, user_avg_days_between, prod_total_purchases, prod_reorder_rate, orders_since_last_purchase]
    feature_cols = [
        'up_total_bought', 
        'user_total_orders', 
        'user_avg_days_between', 
        'prod_total_purchases', 
        'prod_reorder_rate', 
        'orders_since_last_purchase'
    ]
    
    X = df[feature_cols]
    X_scaled = _scaler.transform(X)
    X_lstm = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))

    # 5. Predict
    probs = _model.predict(X_lstm).ravel()
    df['score'] = probs

    # 6. Format Output
    recommendations = df.sort_values('score', ascending=False).head(top_n)
    
    result = []
    for _, row in recommendations.iterrows():
        result.append({
            "product_id": int(row['product_id']),
            "product_name": str(row.get('product_name', f"Product {int(row['product_id'])}")),
            "confidence": round(float(row['score']), 3),
            "reorder_probability": "High" if row['score'] > 0.7 else "Medium" if row['score'] > 0.4 else "Low"
        })

    return result
